extends Node
class_name EventsBus

signal time_tick(minutes: int)
signal hour_changed(hour: int)
signal day_started(day_index: int)
signal day_ending
signal season_changed(season: String)
signal weather_changed(weather_id: String)
signal tide_changed(h: float)
signal item_added(id: String, count: int)
signal inventory_changed
signal farm_changed
signal money_changed(amount: int)
signal crop_harvested(id: String, quality: int)
signal fish_caught(id: String, quality: int, size: float)
signal body_spawned(id: String)
signal body_moved(id: String, where: String)
signal body_examined(id: String)
signal body_buried(id: String, quality: int)
signal body_identified(id: String, correct: bool)
signal ghost_laid_to_rest(id: String)
signal lamp_lit(on_time: bool)
signal night_resolved(report: Dictionary)
signal ship_passed(ship: String)
signal ship_wrecked(ship: String)
signal npc_talked(id: String)
signal gift_given(npc: String, item: String, reaction: String)
signal heart_event_seen(id: String)
signal quest_started(id: String)
signal quest_step_done(id: String)
signal quest_completed(id: String)
signal level_up(skill: String, level: int)
signal node_unlocked(id: String)
signal blessing_gained(id: String)
signal achievement_unlocked(id: String)
signal festival_started(id: String)
signal map_entered(id: String)
signal enemy_killed(id: String)
signal boss_defeated(id: String)
signal player_moved(map_id: String, tile: Vector2i)
signal debug_message(text: String)
